version: '3.8'

services:
  mysql:
    platform: linux/amd64
    build: .
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=sample_database
      - MYSQL_ALLOW_EMPTY_PASSWORD=true